import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Check,Search,Type,Undo2,Redo2,X} from 'lucide-react';
import {cadIcons,categoryIcons,type CadIconComponent} from './CadIcons';
import {CadToolbar} from './CadToolbar';

type Command={id:string;label:string;icon:CadIconComponent;help:string};
const c=(id:string,label:string,icon:CadIconComponent,help:string):Command=>({id,label,icon,help});
export const commandGroups:Record<string,Command[]>={
 Sketch:[c('rectangle','Rectangle',cadIcons['rectangle'],'Add a dimensioned rectangle sketch on a work plane.'),c('circle','Circle',cadIcons['circle'],'Add a dimensioned circle on a work plane.'),c('line','Line',cadIcons['line'],'Draw and dimension a closed line profile on a work plane.'),c('arc','Arc',cadIcons['arc'],'Draw a circular arc.'),c('spline','Spline',cadIcons['spline'],'Draw a curve through control points.'),c('dimension','Smart Dimension',cadIcons['dimension'],'Set sketch sizes or position a rectangle from a parallel model edge.'),c('constraints','Constraints',cadIcons['constraints'],'Apply sketch relations.')],
 Solid:[c('sketch','Sketch',cadIcons['sketch'],'Select a planar face to sketch on it, or choose a datum plane.'),c('extrude','Extrude',cadIcons['extrude'],'Extrude a sketch and join it to the body.'),c('revolve','Revolve',cadIcons['revolve'],'Revolve a profile about an axis.'),c('sweep','Sweep',cadIcons['sweep'],'Sweep a profile along a path.'),c('loft','Loft',cadIcons['loft'],'Blend profiles into a solid.'),c('cut','Extruded cut',cadIcons['cut'],'Remove material using a sketch.'),c('hole','Hole',cadIcons['hole'],'Add a circle sketch and through-cut on a work plane.'),c('fillet','Fillet',cadIcons['fillet'],'Round the native part’s outside corners or rims.'),c('chamfer','Chamfer',cadIcons['chamfer'],'Bevel selected edges.'),c('shell','Shell',cadIcons['shell'],'Hollow a solid to a wall thickness.'),c('draft','Draft',cadIcons['draft'],'Taper faces about a neutral plane.'),c('linear-pattern','Linear pattern',cadIcons['linear-pattern'],'Repeat features along a direction.'),c('circular-pattern','Circular pattern',cadIcons['circular-pattern'],'Repeat features around an axis.'),c('mirror','Mirror',cadIcons['mirror'],'Reflect features across a plane.'),c('measure','Measure',cadIcons['measure'],'Measure exact STEP faces and edges.')],
 Surface:[c('surface-extrude','Extruded surface',cadIcons['surface-extrude'],'Extrude an open profile.'),c('surface-revolve','Revolved surface',cadIcons['surface-revolve'],'Revolve an open profile.'),c('surface-sweep','Swept surface',cadIcons['surface-sweep'],'Sweep a profile along a path.'),c('surface-loft','Lofted surface',cadIcons['surface-loft'],'Blend section curves.'),c('boundary','Boundary surface',cadIcons['boundary'],'Build between boundary curves.'),c('offset','Offset surface',cadIcons['offset'],'Offset selected faces.'),c('trim','Trim surface',cadIcons['trim'],'Trim with an intersecting surface.'),c('knit','Knit surface',cadIcons['knit'],'Join adjacent surfaces.'),c('fill','Fill surface',cadIcons['fill'],'Fill a closed boundary.'),c('extend','Extend surface',cadIcons['extend'],'Extend surface edges.')],
 'Sheet Metal':[c('base-flange','Base flange',cadIcons['base-flange'],'Build a sheet from a profile.'),c('convert-sheet','Convert to sheet metal',cadIcons['convert-sheet'],'Define thickness and bends.'),c('edge-flange','Edge flange',cadIcons['edge-flange'],'Add a flange along an edge.'),c('miter','Miter flange',cadIcons['miter'],'Build flanges along a path.'),c('hem','Hem',cadIcons['hem'],'Fold a sheet edge.'),c('jog','Jog',cadIcons['jog'],'Offset a region of sheet.'),c('bend','Sketched bend',cadIcons['bend'],'Bend along a sketch line.'),c('relief','Corner relief',cadIcons['relief'],'Add bend corner clearance.'),c('forming','Forming tool',cadIcons['forming'],'Form a localized sheet feature.'),c('tab-slot','Tab and slot',cadIcons['tab-slot'],'Create joining tabs and slots.'),c('unfold','Unfold',cadIcons['unfold'],'Unfold selected bends.'),c('fold','Fold',cadIcons['fold'],'Refold selected bends.'),c('flatten','Flatten',cadIcons['flatten'],'Create the developed flat pattern.')],
};

export function ToolButton({command,reason,onClick,showLabel=false,active=false}:{active?:boolean;command:Command;reason?:string;onClick:()=>void;showLabel?:boolean}){
  const [position,setPosition]=useState<{left:number;top:number}|null>(null);const button=useRef<HTMLButtonElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  function close(){if(timer.current)clearTimeout(timer.current);setPosition(null);}
  function leave(){if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(close,150);}
  function open(){if(timer.current)clearTimeout(timer.current);const r=button.current?.getBoundingClientRect();if(r)setPosition({left:Math.max(8,Math.min(r.left,window.innerWidth-248)),top:Math.min(r.bottom+8,window.innerHeight-125)});}
  useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
  useEffect(()=>{if(!position)return;const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('keydown',escape);window.addEventListener('resize',close);window.addEventListener('scroll',close,true);return()=>{window.removeEventListener('keydown',escape);window.removeEventListener('resize',close);window.removeEventListener('scroll',close,true);};},[position]);
  const Icon=command.icon;
  return <><button ref={button} className={"authoring-tool"+(active?" is-active":"")} aria-pressed={active||undefined} aria-label={command.label} aria-disabled={!!reason} aria-describedby={position?'tool-help-'+command.id:undefined} onMouseEnter={()=>{timer.current=setTimeout(open,400);}} onMouseLeave={leave} onFocus={open} onBlur={close} onClick={()=>{if(!reason){close();onClick();}else open();}}><Icon size={24} strokeWidth={1.55}/>{showLabel&&<span>{command.label}</span>}</button>{position&&createPortal(<div className="authoring-tooltip" id={'tool-help-'+command.id} role="tooltip" style={position} onMouseEnter={open} onMouseLeave={leave}><strong>{command.label}</strong><span>{reason||command.help}</span></div>,document.body)}</>;
}

type Props={sketchMode?:boolean;sketchTool?:string;sketchReady?:boolean;version?:number;native:boolean;hasModel:boolean;signedIn:boolean;locked:boolean;readOnly:boolean;canUndo:boolean;canRedo:boolean;onCommand:(id:string)=>void;onUndo:()=>void;onRedo:()=>void};
export function AuthoringToolbar(p:Props){
  const [family,setFamily]=useState('Solid'),[labels,setLabels]=useState(()=>{try{return localStorage.getItem('cad-tool-labels')==='true';}catch{return false;}}),[query,setQuery]=useState('');
  const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null),search=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(p.sketchMode)setFamily('Sketch');},[p.sketchMode]);
  function reason(command:Command){
    if(p.sketchMode&&['extrude','cut'].includes(command.id)&&!p.sketchReady)return 'Draw a valid closed profile first.';
    if(p.sketchMode&&['rectangle','circle','line','dimension','extrude','cut'].includes(command.id))return undefined;
    if(!['sketch','rectangle','circle','line','extrude','cut','hole','fillet','measure'].includes(command.id))return 'Not available yet: this modeling operation is not implemented.';
    if(command.id==='fillet'&&(p.version||1)>=2)return 'General edge fillets are not available yet. Existing version-one fillets remain editable in History.';
    if(command.id==='line'&&!p.native)return 'Create a part first, then add a closed line sketch.';
    if(p.locked)return 'Apply or cancel the current edit first.';
    if(command.id==='measure')return p.hasModel?undefined:'Open a part to measure.';
    if(!p.signedIn)return 'Sign in to create and edit native parts.';
    if(p.readOnly)return 'This shared project is read-only.';
    if(!p.native&&!['sketch','rectangle','circle'].includes(command.id))return 'Create a native part first. Imported STEP feature editing is not available.';
    return undefined;
  }
  function close(){dialog.current?.close();trigger.current?.focus();}
  return <div className="authoring-commands"><div className="authoring-families" role="tablist" aria-label="CAD tool category" onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const names=Object.keys(commandGroups);e.preventDefault();const i=names.indexOf(family);const next=names[e.key==='Home'?0:e.key==='End'?names.length-1:(i+(e.key==='ArrowRight'?1:-1)+names.length)%names.length];setFamily(next);e.currentTarget.querySelector<HTMLButtonElement>(`[data-family="${next}"]`)?.focus();}}>{Object.keys(commandGroups).map(name=>{const CategoryIcon=categoryIcons[name];return <button key={name} data-family={name} role="tab" aria-selected={name===family} tabIndex={name===family?0:-1} onClick={()=>setFamily(name)}><CategoryIcon size={22}/><span>{name}</span></button>;})}<button ref={trigger} className="authoring-search" aria-label="Find a tool" onClick={()=>{setQuery('');dialog.current?.showModal();search.current?.focus();}}><Search size={18}/></button></div>
    <CadToolbar className={'authoring-strip'+(labels?' with-labels':'')} label={family+' tools'}>{[...commandGroups[family].filter(c=>c.id!=='dimension'),...(p.sketchMode&&family==='Sketch'?commandGroups.Solid.filter(c=>c.id==='extrude'||c.id==='cut'):[])].map(command=><ToolButton key={command.id} command={command} active={p.sketchMode&&p.sketchTool===command.id} reason={reason(command)} showLabel={labels} onClick={()=>p.onCommand(command.id)}/>)}<span className="authoring-separator"/><ToolButton command={c('undo','Undo geometry',Undo2,'Undo the last applied geometry edit.')} reason={p.canUndo&&!p.locked?undefined:'No geometry edit to undo.'} onClick={p.onUndo}/><ToolButton command={c('redo','Redo geometry',Redo2,'Redo an undone geometry edit.')} reason={p.canRedo&&!p.locked?undefined:'No geometry edit to redo.'} onClick={p.onRedo}/><button className="authoring-tool labels-toggle" aria-label="Show tool names" aria-pressed={labels} onClick={()=>{setLabels(!labels);try{localStorage.setItem('cad-tool-labels',String(!labels));}catch{}}}><Type size={18}/></button></CadToolbar>
    <dialog ref={dialog} className="tool-search-dialog" onCancel={close} onClick={e=>{if(e.target===dialog.current)close();}}><div className="cad-editor-heading"><h2>Find a tool</h2><button className="icon-button" aria-label="Close tool search" onClick={close}><X size={18}/></button></div><input ref={search} aria-label="Search CAD tools" placeholder="Hole, surface, flange…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="tool-search-results">{Object.entries(commandGroups).flatMap(([category,commands])=>commands.filter(cmd=>(category+' '+cmd.label).toLowerCase().includes(query.toLowerCase())).map(command=><button key={command.id} aria-disabled={!!reason(command)} onClick={()=>{if(!reason(command)){close();p.onCommand(command.id);}}}><command.icon size={24}/><span><strong>{command.label}</strong><small>{reason(command)||category}</small></span>{!reason(command)&&<Check size={14}/>}</button>))}{!Object.entries(commandGroups).some(([category,commands])=>commands.some(cmd=>(category+' '+cmd.label).toLowerCase().includes(query.toLowerCase())))&&<p className="muted">No matching tools.</p>}</div></dialog>
  </div>;
}
