import type {ReactNode} from 'react';
import {ArrowLeft,Box,ChevronRight,Folder,PanelLeftClose,PanelLeftOpen,Plus,Share2} from 'lucide-react';
import type {Model} from './api';

type Props={tab:'chat'|'projects';onTab:(tab:'chat'|'projects')=>void;collapsed:boolean;onToggle:()=>void;workspace:any;folder:string|null;onFolder:(id:string|null)=>void;onNewFolder:()=>void;onOpenProject:(project:any)=>void;onPublishProject:(project:any)=>void;onShareFolder:(id:string)=>void;model:Model|null;sharedView:boolean;onSharedView:(shared:boolean)=>void;search:string;onSearch:(search:string)=>void;readOnly:boolean;chat:ReactNode};

export function WorkspaceSidebar(p:Props){
  const folders=p.workspace.folders||[],folderIds=new Set(folders.map((f:any)=>f.id));
  const visibleFolders=folders.filter((f:any)=>p.folder?f.parent_id===p.folder:!folderIds.has(f.parent_id));
  const source=p.sharedView?p.workspace.shared||[]:p.workspace.projects||[];
  const projects=source.filter((project:any)=>(p.folder?project.folder_id===p.folder:p.sharedView||!folderIds.has(project.folder_id))&&project.name.toLowerCase().includes(p.search.toLowerCase()));
  const folderName=folders.find((f:any)=>f.id===p.folder)?.name;
  return <aside className={p.collapsed?'workspace-sidepanel is-collapsed':'workspace-sidepanel'} aria-label="Workspace menu">
    <div className="workspace-panel-heading">{p.collapsed?<strong className="workspace-panel-title">Workspace</strong>:<div className="workspace-side-tabs" role="tablist" aria-label="Workspace view" onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?'chat':event.key==='End'?'projects':p.tab==='chat'?'projects':'chat';p.onTab(next);event.currentTarget.querySelector<HTMLButtonElement>('#workspace-'+next+'-tab')?.focus();}}><button id="workspace-chat-tab" role="tab" aria-controls="workspace-chat-panel" aria-selected={p.tab==='chat'} className={p.tab==='chat'?'active':''} onClick={()=>p.onTab('chat')}>Chat</button><button id="workspace-projects-tab" role="tab" aria-controls="workspace-projects-panel" aria-selected={p.tab==='projects'} className={p.tab==='projects'?'active':''} onClick={()=>p.onTab('projects')}>Projects</button></div>}<button className="workspace-panel-toggle" aria-label={p.collapsed?'Expand workspace menu':'Minimize workspace menu'} title={p.collapsed?'Expand workspace menu':'Minimize workspace menu'} aria-expanded={!p.collapsed} aria-controls="workspace-side-content" onClick={p.onToggle}>{p.collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</button></div>
    <div id="workspace-side-content" className="workspace-side-content" hidden={p.collapsed}>
    <div className="workspace-chat-panel" id="workspace-chat-panel" role="tabpanel" aria-labelledby="workspace-chat-tab" hidden={p.tab!=='chat'}>{p.chat}</div>
    <div className="workspace-projects" id="workspace-projects-panel" role="tabpanel" aria-labelledby="workspace-projects-tab" hidden={p.tab!=='projects'}>
      {!p.readOnly&&<div className="workspace-project-controls"><select aria-label="Project ownership" value={p.sharedView?'shared':'mine'} onChange={event=>{p.onSharedView(event.target.value==='shared');p.onFolder(null);}}><option value="mine">My projects</option><option value="shared">Shared with me</option></select>{!p.sharedView&&<button className="text-link" onClick={p.onNewFolder}><Plus size={15}/>New folder</button>}</div>}
      {p.folder&&<div className="workspace-projects-heading"><button className="text-link" aria-label="Back to parent folder" onClick={()=>p.onFolder(folders.find((f:any)=>f.id===p.folder)?.parent_id||null)}><ArrowLeft size={15}/></button><h2>{folderName}</h2>{!p.readOnly&&<button className="text-link" aria-label="Share folder" title="Share folder" onClick={()=>p.onShareFolder(p.folder!)}><Share2 size={15}/></button>}</div>}
      <label className="sr-only" htmlFor="workspace-project-search">Search projects</label><input id="workspace-project-search" className="workspace-project-search" placeholder="Search projects…" value={p.search} onChange={e=>p.onSearch(e.target.value)}/>
      <div className="workspace-project-list">{!p.sharedView&&visibleFolders.length>0&&<h3>Folders</h3>}{!p.sharedView&&visibleFolders.map((f:any)=><button className="workspace-project-item" key={f.id} onClick={()=>p.onFolder(f.id)}><span className="workspace-row-icon"><Folder size={17}/></span><span>{f.name}<small>{source.filter((project:any)=>project.folder_id===f.id).length} projects</small></span><ChevronRight size={16}/></button>)}{projects.length>0&&<h3>{p.folder?'Files':p.sharedView?'Shared projects':'Recent files'}</h3>}{projects.map((project:any)=><div className="workspace-project-row" key={project.id}><button className={p.model?.project?.id===project.id?'workspace-project-item selected':'workspace-project-item'} onClick={()=>p.onOpenProject(project)}><span className="workspace-row-icon"><Box size={17}/></span><span>{project.name}<small>{p.sharedView?'Shared project':project.published?'Published revision':'Private draft'}</small></span><ChevronRight size={16}/></button>{!p.readOnly&&!p.sharedView&&!project.published&&<button className="workspace-publish" onClick={()=>p.onPublishProject(project)}>Publish</button>}</div>)}{!visibleFolders.length&&!projects.length&&<p className="workspace-project-empty">{p.search?'No matching projects.':p.sharedView?'No shared projects yet.':'No projects here yet. Open a part, then save a draft.'}</p>}</div>
    </div>
    </div>
  </aside>;
}
