import type {ReactNode} from 'react';
import {ArrowLeft,Box,ChevronRight,Folder,Plus,Share2} from 'lucide-react';
import type {Model} from './api';

type FileProps={onRenameProject:(project:any)=>void;workspace:any;folder:string|null;onFolder:(id:string|null)=>void;onNewFolder:()=>void;onOpenProject:(project:any)=>void;onPublishProject:(project:any)=>void;onShareFolder:(id:string)=>void;model:Model|null;sharedView:boolean;onSharedView:(shared:boolean)=>void;search:string;onSearch:(search:string)=>void;readOnly:boolean};

export function WorkspaceSidebar(p:{tab:'chat'|'history';onTab:(tab:'chat'|'history')=>void;chat:ReactNode;history:ReactNode}){
  return <aside className="workspace-sidepanel" aria-label="CAD editing workspace"><div className="workspace-panel-heading"><div className="workspace-side-tabs" role="tablist" aria-label="Editing method" onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?'history':e.key==='End'?'chat':p.tab==='chat'?'history':'chat';p.onTab(next);e.currentTarget.querySelector<HTMLButtonElement>('#workspace-'+next+'-tab')?.focus();}}>{(['history','chat'] as const).map(tab=><button key={tab} id={'workspace-'+tab+'-tab'} role="tab" aria-selected={p.tab===tab} tabIndex={p.tab===tab?0:-1} aria-controls={'workspace-'+tab+'-panel'} onClick={()=>p.onTab(tab)}>{tab==='history'?'History':'Chat'}</button>)}</div></div><div className="workspace-side-content"><><section id="workspace-history-panel" role="tabpanel" aria-labelledby="workspace-history-tab" hidden={p.tab!=='history'}>{p.history}</section><section id="workspace-chat-panel" className="workspace-chat-panel" role="tabpanel" aria-labelledby="workspace-chat-tab" hidden={p.tab!=='chat'}>{p.chat}</section></></div></aside>;
}

export function WorkspaceFiles(p:FileProps){
  const folders=p.workspace.folders||[],folderIds=new Set(folders.map((f:any)=>f.id));
  const visibleFolders=folders.filter((f:any)=>(p.folder?f.parent_id===p.folder:!folderIds.has(f.parent_id))&&(!p.search||f.name.toLowerCase().includes(p.search.toLowerCase())));
  const source=p.sharedView?p.workspace.shared||[]:p.workspace.projects||[];
  const projects=source.filter((project:any)=>(!p.folder||project.folder_id===p.folder||!!p.search)&&project.name.toLowerCase().includes(p.search.toLowerCase()));
  const folderName=folders.find((f:any)=>f.id===p.folder)?.name;
  return (
    <div className="workspace-projects" id="workspace-projects-panel">
      {!p.readOnly&&<div className="workspace-project-controls"><select aria-label="Project ownership" value={p.sharedView?'shared':'mine'} onChange={event=>{p.onSharedView(event.target.value==='shared');p.onFolder(null);}}><option value="mine">My projects</option><option value="shared">Shared with me</option></select>{!p.sharedView&&<button className="text-link" onClick={p.onNewFolder}><Plus size={15}/>New folder</button>}</div>}
      {p.folder&&<div className="workspace-projects-heading"><button className="text-link" aria-label="Back to parent folder" onClick={()=>p.onFolder(folders.find((f:any)=>f.id===p.folder)?.parent_id||null)}><ArrowLeft size={15}/></button><h2>{folderName}</h2>{!p.readOnly&&<button className="text-link" aria-label="Share folder" title="Share folder" onClick={()=>p.onShareFolder(p.folder!)}><Share2 size={15}/></button>}</div>}
      <label className="sr-only" htmlFor="workspace-project-search">Search projects</label><input id="workspace-project-search" className="workspace-project-search" placeholder="Search projects…" value={p.search} onChange={e=>p.onSearch(e.target.value)}/>
      <div className="workspace-project-list">{!p.sharedView&&visibleFolders.length>0&&<h3>Folders</h3>}{!p.sharedView&&visibleFolders.map((f:any)=><button className="workspace-project-item" key={f.id} onClick={()=>p.onFolder(f.id)}><span className="workspace-row-icon"><Folder size={17}/></span><span>{f.name}<small>{source.filter((project:any)=>project.folder_id===f.id).length} projects</small></span><ChevronRight size={16}/></button>)}{projects.length>0&&<h3>{p.folder?'Files':p.sharedView?'Shared projects':'Recent files'}</h3>}{projects.map((project:any)=><div className="workspace-project-row" key={project.id}><button className={p.model?.project?.id===project.id?'workspace-project-item selected':'workspace-project-item'} onClick={()=>p.onOpenProject(project)}><span className="workspace-row-icon"><Box size={17}/></span><span>{project.name}<small>{p.sharedView?'Shared project':project.published?'Published revision':'Private draft'}</small></span><ChevronRight size={16}/></button>{!p.readOnly&&!p.sharedView&&<button className="workspace-publish" onClick={()=>p.onRenameProject(project)}>Rename</button>}{!p.readOnly&&!p.sharedView&&!project.published&&<button className="workspace-publish" onClick={()=>p.onPublishProject(project)}>Publish</button>}</div>)}{(!visibleFolders.length||p.sharedView)&&!projects.length&&<p className="workspace-project-empty">{p.search?'No matching projects.':p.sharedView?'No shared projects yet.':'No projects here yet. Open a part, then save a draft.'}</p>}</div>
    </div>
  );
}
